---
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/Edmonton
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /volume1/docker/calibre-web:/config
      - /volume1/data/media/books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
    security_opt:
      - seccomp=unconfined
    labels:
      - homepage.group=Media
      - homepage.name=Calibre
      - homepage.icon=calibre.png
      - homepage.href=http://jumbo.local:8083/
      - homepage.description=Download Ebooks