---
version: "3.7"
services:
  readarr:
    image: cr.hotio.dev/hotio/readarr:nightly
    container_name: readarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/Edmonton
    volumes:
      - /volume1/docker/readarr:/config
      - /volume1/data:/data
    ports:
      - 8787:8787
    restart: unless-stopped
networks: 
  default: 
    external: true
    name: media-network        