---
version: "2.1"
services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/Edmonton
    volumes:
      - /volume1/docker/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
networks: 
  default: 
    external: true
    name: media-network        
