version: '3.7'

services:
  app:
    image: photostructure/server:latest
    ports:
      - '1787:1787/tcp'
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/Edmonton    
      - PS_EXPOSE_NETWORK_WITHOUT_AUTH="true"
    volumes:
      - /volume1/docker/photostructure/config:/ps/config
      - /volume1/docker/photostructure/logs:/ps/logs
      - /volume1/docker/photostructure/tmp:/ps/tmp
      - /volume1/data/media/photos:/ps/library
      - /volume1/photo/DesktopBackup:/mnt/desktop_backup:ro
      - /volume1/photo/Flickr-2025-01-17:/mnt/flickr_backup:ro
      - /volume1/photo/GooglePhotos-2025-01-17:/mnt/google_2025_backup:ro
      - /volume1/photo/GooglePhotos-20201231:/mnt/google_2020_backup:ro
      - /volume1/photo/MobileBackup:/mnt/mobile_backup:ro
      - /volume1/photo/PhotoLibrary:/mnt/synology_photos_backup:ro

    network_mode: host
