version: '3'
services:
  kavita:
    image: kizaing/kavita:latest
    container_name: kavita
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/Edmonton        
    volumes:
      - /volume1/data:/data
      - /volume1/docker/kavita:/kavita/config
    ports:
      - "5678:5000"
    restart: unless-stopped