version: "3"
services:
  navidrome:
    image: deluan/navidrome
    container_name: navidrome
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/Edmonton
    volumes:
      - /volume1/docker/navidrome:/data
      - /volume1/data/media/music:/music:ro
    ports:
      - 4533:4533
    restart: unless-stopped
networks: 
  default: 
    external: true
    name: downloaders
