version: "3.7"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    volumes:
      - /volume1/docker/qbittorrent:/config
      - /volume1/data:/data
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/Edmonton    
      - WEBUI_PORT=8200

## Do Not Change Network for qBittorrent
## qBittorrent MUST always use a VPN / Secure Internet connection
## https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md
    network_mode: "container:gluetun"