---
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/Edmonton
      - DOCKER_MODS=lscr.io/linuxserver/mods:universal-calibre-v7.16.0
    volumes:
      - /volume1/configs/calibre-web:/config
      - /volume1/data/import/books:/cwa-book-ingest
      - /volume1/data/media/books:/calibre-library   
      #- /path/to/your/gmail/credentials.json:/app/calibre-web/gmail.json #Optional
    ports:
      - 8083:8083 # Change the first number to change the port you want to access the Web UI, not the second
    restart: unless-stopped
    