---
version: '2'
services:
  plex:
    image: plexinc/pms-docker 
    container_name: plex
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp    
    environment:
      - PUID=1027
      - PGID=100
      - PLEX_CLAIM= #optional
      - TZ=America/Edmonton
    hostname: Jumbo
    volumes:
      - /volume1/docker/plex/config:/config
      - /volume1/docker/plex/transcode:/transcode
      - /volume1/data/media:/data/media
    devices:
      - "/dev/dri:/dev/dri"
    labels:
      - homepage.group=Popular
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.href=http://jumbo.local:32400/
      - homepage.description=Plex Media Server      
networks: 
  default: 
    external: true
    name: downloaders