version: "2.1"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/Edmonton
    volumes:
      - /volume1/docker/lidarr:/config
      - /volume1/data:/data
    ports:
      - 8686:8686
    restart: unless-stopped
networks: 
  default: 
    external: true
    name: media-network  