version: '3.3'
services:
  icloudpd-mike:
    image: boredazfcuk/icloudpd:latest
    container_name: icloudpd-mike
    restart: always
    environment:
      - TZ=America/Edmonton            
      - user_id=1027
      - group_id=100
      - apple_id=mike@aream.ca
      - authentication_type=2FA
      - 'folder_structure={:%Y/%m}'
      - notification_days=7
      - synchronisation_interval=86400
      - 'download_path=/icloud'
      - skip_check=false
      - auto_delete=true
    network_mode: host
    volumes:
      - '/volume1/configs/icloudpd/mike_config:/config'
      - '/volume1/photo/icloud/mike:/icloud'
  icloudpd-sheila:
    image: boredazfcuk/icloudpd:latest
    container_name: icloudpd-sheila
    restart: always
    environment:
      - TZ=America/Edmonton            
      - user_id=1027
      - group_id=100
      - apple_id=sheila@aream.ca
      - authentication_type=2FA
      - 'folder_structure={:%Y/%m}'
      - notification_days=7
      - synchronisation_interval=86400
      - 'download_path=/icloud'
      - skip_check=false
      - auto_delete=true
    network_mode: host
    volumes:
      - '/volume1/configs/icloudpd/sheila_config:/config'
      - '/volume1/photo/icloud/sheila:/icloud'