version: "3.7"

networks:
  media-network:
    name: media-network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.29.10.0/24
        gateway: 172.29.10.1

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - "8200:8200"   # WebUI Portal: qBittorrent
      - "6881:6881/tcp"
      - "6881:6881/udp"
    volumes:
      - /volume1/docker/gluetun:/gluetun
      - /volume1/docker/gluetun/getflix/Canada-Toronto_TCP1194_SMART.ovpn:/openvpn/custom.ovpn:ro
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/Edmonton    
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_CUSTOM_CONFIG=/openvpn/custom.ovpn
      - OPENVPN_USER=VPN-218333
      - OPENVPN_PASSWORD=WLWRFTFT
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=   

# NOTE: Gluetun VPN container MUST ONLY connect to the media-network

    networks:
      - media-network
